Update create-release.yml

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -15,7 +15,7 @@ jobs:
         
       - name: Is Branch Main
         if: github.event.ref_name != 'main'
-        run: echo "::error title=Wrong Branch::Branch should be Main"
+        run: echo "::error title=Wrong Branch::Branch should be Main" | exit 1
 
       # Setup Node.js environment
       - name: Setup Node.js
